# Generated by Django 5.2.3 on 2025-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('formacao', models.CharField(max_length=45)),
            ],
        ),
    ]
