# Generated by Django 5.2.3 on 2025-07-03 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('CPF', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=45)),
                ('pai', models.CharField(max_length=45)),
                ('mae', models.CharField(max_length=45)),
                ('data_nasc', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('carga_horaria', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('CPF', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=45)),
                ('data_nasc', models.DateField(null=True)),
                ('formacao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=45)),
                ('carga_horaria', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.disciplina')),
            ],
        ),
    ]
