# Generated by Django 5.2.3 on 2025-07-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='mae_aluno',
            new_name='mae',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='pai_aluno',
            new_name='pai',
        ),
    ]
