# Generated by Django 5.2.3 on 2025-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='CPF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.IntegerField(default=0),
        ),
    ]
