# Generated by Django 5.2.3 on 2025-07-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
