# Generated by Django 5.2.3 on 2025-07-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0002_rename_mae_aluno_aluno_mae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
